// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/blog/[slug].tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/silent-tweets.tsx";
import * as $4 from "./routes/social.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/blog/[slug].tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/silent-tweets.tsx": $3,
    "./routes/social.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
